Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs14.x
    Handler: index.handler

Description:
  "SAM Template for Lambda Function URL demo."

Resources:
  LambdaFurlNoAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri: response/function.zip
      Layers:
        - !Ref LambdaFurlUuidLayer
      FunctionUrlConfig:
        AuthType: NONE
        Cors: 
          AllowOrigins:
            - '*'
          AllowMethods:
            - GET
          AllowHeaders:
            - keep-alive
            - Content-type
  
  LambdaFurlIAMFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri: response/function.zip
      Layers:
        - !Ref LambdaFurlUuidLayer
      FunctionUrlConfig:
        AuthType: AWS_IAM
        Cors: 
          AllowOrigins:
            - '*'
          AllowMethods:
            - GET
          AllowHeaders:
            - keep-alive
            - Content-type

  LambdaFurlIAMResourceBasedPolicy:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunctionUrl
      FunctionName: !GetAtt LambdaFurlIAMFunction.Arn
      FunctionUrlAuthType: AWS_IAM
      Principal: !Sub arn:aws:iam::${AWS::AccountId}:user/jeong
            
  LambdaFurlUuidLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/uuid-layer.zip
      CompatibleRuntimes:
        - nodejs12.x
        - nodejs14.x
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: nodejs14.x


Outputs:
  LambdaFurlNoAuthFunctionEndpoint:
    Description: "Endpoint of the No Auth Lambda Function."
    Value: 
      !GetAtt LambdaFurlNoAuthFunctionUrl.FunctionUrl
  LambdaFurlIAMFunctionEndpoint:
    Description: "Endpoint of the IAM Auth Lambda Function."
    Value: 
      !GetAtt LambdaFurlIAMFunctionUrl.FunctionUrl