Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs14.x
    Handler: index.handler

Description:
  "SAM Template for Lambda Function URL demo."

Resources:
  LambdaFurlNoAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri: response/function.zip
      Layers:
        - !Ref LambdaFurlUuidLayer
      FunctionUrlConfig:
        AuthType: NONE
        Cors: 
          AllowOrigins:
            - '*'
          AllowMethods:
            - GET
          AllowHeaders:
            - keep-alive
            - Content-type

  LambdaFurlRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri: request/function.zip
      Layers:
        - !Ref LambdaFurlUuidLayer
      Environment:
        Variables:
          FUNCTION_URL: 
            !GetAtt LambdaFurlNoAuthFunctionUrl.FunctionUrl

  LambdaFurlUuidLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/uuid-layer.zip
      CompatibleRuntimes:
        - nodejs12.x
        - nodejs14.x
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: nodejs14.x


Outputs:
  LambdaFurlNoAuthFunctionEndpoint:
    Description: "Endpoint of the No Auth Lambda Function."
    Value: 
      !GetAtt LambdaFurlNoAuthFunctionUrl.FunctionUrl